### ISSUE TITLE
Cannot realize a defined resource type 

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#98]
For instance   `realize (Tool::Setpass[$user])` is failing with
```
 Could not apply this resource override : realize(Tool::Setpass[fixmystreet])
```
where `tool::setpass` is a defined resource.

PS: I should include a test here for reference but note that this problem has been reported to me by another tier as well.

Here is the link to the related puppet doc:
https://docs.puppetlabs.com/guides/virtual_resources.html#virtual-define-based-resources

**Comment by bartavelle** [comment]
What is the expected behavior in that case ? A noop ?

**Comment by PierreR** [comment]
So if I copy what the puppet doc is saying : 
```
define msg($arg) {
  notify { "$name: $arg": }
}
@msg { test1: arg => arg1 }
@msg { test2: arg => arg2 }

With the above definitions, neither of the msg resources will be applied to a node unless it realizes them, e.g.:

realize( Msg[test1], Msg[test2] )
```

**Comment by bartavelle** [comment]
Yeah but what about this :

```
define msg($arg) {
  notify { "$name: $arg": }
}
msg { test1: arg => arg1 }
realize(Msg[test1])
```

I suppose the `realize` should do nothing here ... even though I like it when it throws an error :)

**Comment by PierreR** [comment]
Is it what is happening to me ?

I haven't fully checked that @tool::setpass is actually executed. This is the code:
```
  if $password {
    @tool::setpass {
      $name:
        pwdhash => $password,
        require => User[$name];
    }
  }
```

**Comment by bartavelle** [comment]
Oh I think I did not understand the problem. I just pushed something (without testing it ... sorry lack of time) that should help narrow the problem.

If this persists, it probably means the `if` condition is not true ...

**Comment by PierreR** [comment]
Still no luck. This is the error:
```
Problem with fixmystreet_prod : Could not apply this resource override : realize(Tool::Setpass[fixmystreet]) # "./modules/application/manifests/profile/django/users.pp" (line 40, column 5),no matching resource was found.
```

I am actually sure now that the virtual resource is defined because I am calling this way:
```
  if defined(Tool::Setpass[$user]) {
    realize (Tool::Setpass[$user])
  }
```

**Comment by PierreR** [comment]
By the way this is not my puppet code actually ...

I don't know much what's going on but apparently the $user is not even realized so I don't see how it makes sense to set a pass for it ;-)

I will try to test this with a more coherent use case and let you know ...

**Comment by PierreR** [comment]
I have made up a simple example and the current implementation seems totally wrong with respect to defined resource (or I am missing something ...)

First anomaly:
```
class test::testme (
){
@test::msg { test1: arg => arg1 }
#realize(Test::Msg[test1])
}
```
```
define test::msg($arg) {
  notify { "$name: $arg": }
}
```

#### The virtual defined resource is output by puppetresources :
```
 puppetresources -p . -o default
class {
  test::testme: # "./manifests/site.pp" (line 2, column 3) default [Scope []]
    ;
}
notify {
  $name: arg1: # "./modules/test/manifests/msg.pp" (line 2, column 12) default [Scope [Test::Msg[test1]
                                                                                      ,class test::testme]]
    require => Test::Msg[test1];
}
stage {
  main: # "dummy" (line 1, column 1) default [Scope []]
    ;
}
```

#### if I remove the comment in front of realize, it should pass but it fails:
```
@panjaro ~/tmp/puppet > puppetresources -p . -o default
Problem with default : Could not apply this resource override : realize(Test::Msg1[test1]) # "./modules/test/manifests/testme.pp" (line 5, column 1),no matching resource was found.
```
This passes with `puppet apply`

#### if I remove the `@` it is still failing ... and in that case it should fail.

This passes with `puppet apply` in puppet 3.3.1 though it is said [here](https://docs.puppetlabs.com/puppet/latest/reference/lang_virtual.html#collectors-vs-the-realize-function)  that it should fail (if I am reading this correctly)

**Comment by PierreR** [comment]
I have tried to debug this looking at the content of [`curmap`](https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter.hs#L266)

It seems that its content is the same whether you add `@` or not. `@` doesn't seem to trigger any virtuality at all on defined resource.

**Comment by bartavelle** [comment]
Wow that's a huge bug, looking at it

**Comment by bartavelle** [comment]
It looks like non-native types would always be expanded, regardless of their virtuality ! I just pushed something that should help.

**Comment by PierreR** [comment]
Yes it seems to work much better ;-)
